### ISSUE TITLE
Image information is incorrect for some datasets

### ISSUE THREAD

**Issue by hjmjohnson** [npnl/ATLAS#1]
![image](https://user-images.githubusercontent.com/313970/46383352-8fc00700-c675-11e8-88c3-f3cdc1af9b99.png)

The picture above is in micron

The picture below is from Slicer.   NOTE THE MASK AND THE IMAGE DO NOT OCCUPY THE SAME SPACE!:
![image](https://user-images.githubusercontent.com/313970/46383453-0eb53f80-c676-11e8-91d5-fb93135a39d4.png)

**Comment by hjmjohnson** [comment]
@npnl @amitasviper @leiliew @kaoriito  I would like to use this data to test a new automated lesion identification tool, but in it's current state the data inconsistencies will prevent that use.  I would appreciate any information you have regarding the mis-alignment of the label maps and image data.

**Comment by leiliew** [comment]
Thank you for this comment @hjmjohnson! I assume you are using the raw data downloaded from ICPSR? We are aware of this and will be uploading new data in the upcoming week or so - will update this issue when it is fixed. In any case, it should only affect c0001 and c0002 from the dataset, so if you wanted to begin processing with c0003 you should be ok. Let me know if you find this in any other cohorts in our dataset, and thank you again for posting this issue!

**Comment by hjmjohnson** [comment]
Thank you.  I look forward to having access to the updated data.

**Comment by leiliew** [comment]
Hello @hjmjohnson! Sorry for the long delay; the uploading at the archive site took much longer than expected. In any case, the images in c0001 and c0002 should now be fixed. You can download it from here - it should be ATLAS release 1.2: https://www.icpsr.umich.edu/icpsrweb/ADDEP/studies/36684 Please let us know if you have any other questions, issues, or comments - thanks!
