### ISSUE TITLE
Unable to extract the tar.gz file

### ISSUE THREAD

**Issue by psm1002** [npnl/ATLAS#15]
The archive file is either in unknown format or damaged.

**Comment by leiliew** [comment]
Please make sure you use the newer ccrypt version of the download: https://fcon_1000.projects.nitrc.org/indi/retro/atlas_download.html

**Comment by psm1002** [comment]
> Please make sure you use the newer ccrypt version of the download: https://fcon_1000.projects.nitrc.org/indi/retro/atlas_download.html

**Comment by psm1002** [comment]
Thank you was able to extract files
