### ISSUE TITLE
decryption doesn't seem to work

### ISSUE THREAD

**Issue by wwgraves** [npnl/ATLAS#2]
This seems like a potentially great resource, if only I could get the data to decrypt.
When I try to follow the instructions on your website, I get an error. Here’s what happens.

First I use this command from the ATLAS Data Download website:
openssl aes-256-cbc -d -a -in ATLAS_R1.1_encrypted.tar.gz -out ATLAS_R1.1.tar.gz

Then I get this prompt:
enter aes-256-cbc decryption password:

When I enter the encryption key you sent, this happens:
bad decrypt

I'd appreciate any help you can give. Since this is published as an "open source" dataset in Nature Scientific Data, it would be great if it were actually accessible.
I've asked this question to the first author of the associated paper, Sook-Lei Liew, who referred me to Lei Ai, from whom I never received a response despite multiple follow ups.

**Comment by leiliew** [comment]
Thanks for reporting this issue Will! We have resolved this by providing a different link to the data source. If others have this issue, please email npnl@usc.edu and sliew@usc.edu. Thank you!
