### ISSUE TITLE
Download link and decryption code

### ISSUE THREAD

**Issue by vvnkk8** [npnl/ATLAS#3]
Hello,

Firstly, thank you so much for this amazing dataset. However, I haven't received the decryption code for the for, after filling in the Google sheet. Could please confirm if this is the correct link for the download?

http://fcon_1000.projects.nitrc.org/indi/retro/atlas.html

**Comment by leiliew** [comment]
Hello - apologies for the very late reply; this is the correct download, and hopefully you have received the decryption code by now. If not, feel free to fill out the sheet again. Thanks!
