### ISSUE TITLE
About time points  (tXX)

### ISSUE THREAD

**Issue by Angeluz-07** [npnl/ATLAS#5]
Hello. Thanks for the efforts. I have some doubts about the time points specifications.

Does each unit of time point, i.e. (tXX), refers to a week ?. e.g. :  t01 -> one week since stroke, t02 -> two weeks since stroke, and so on. Is suggested as so in the paper, but I would like to confirm.

**Comment by leiliew** [comment]
Thanks for this comment and apologies on the delayed reply; the timepoints can be any time after stroke but just denote that for repeated subjects, which one is first, second, etc. If you have any concerns, I would just use data from t01 (first timepoint per participant).
