### ISSUE TITLE
Unable to Open the dataset

### ISSUE THREAD

**Issue by smiti14** [npnl/ATLAS#6]
I have downloaded the dataset with the encrypting key provided but after the download, the zip folder is not opening and shows there is an error in the opening as the file or format is damaged or the archive is another format. Please guide me on what to do next.

**Comment by xaoyaoo** [comment]
I can't open it, too, indicating that the file is damaged

**Comment by leiliew** [comment]
Hello - if you could please provide more information about the exact inputs you're using and the error you receive, as well as your operating system and version, that will help us help you to troubleshoot. We have people downloading and using the dataset without issues on a daily basis, so it is unlikely the file is damaged.

**Comment by yml-bit** [comment]
I download the ATLAS1.1, when I use the command "openssl aes-256-cbc -md sha256 -d -a -in ATLAS_R1.1_encrypted.tar.gz -out ATLAS_R1.1.tar.gz" and input the keyword,then have the following error:
"*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
bad decrypt
19696:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:570:"

**Comment by 18487083963** [comment]
> Hello - if you could please provide more information about the exact inputs you're using and the error you receive, as well as your operating system and version, that will help us help you to troubleshoot. We have people downloading and using the dataset without issues on a daily basis, so it is unlikely the file is damaged.

**Comment by johannesSX** [comment]
Same problem here. For both ATLAS 1.1 and 2.0 I can not encrypt them.

**Comment by leiliew** [comment]
Hello - do you mean you cannot decrypt? Can you confirm you downloaded it from: http://fcon_1000.projects.nitrc.org/indi/retro/atlas.html We have tested it multiple times, including today, with no decryption errors using the password provided after you fill out the google form listed on the page. Thanks.

**Comment by johannesSX** [comment]
Yes, exactly, I can't decipher it. Tried OpenSSL 1.1.1l on the Mac and got this error:
`*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
bad decrypt
4357725696:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:610:`

I've tried password dozen of times.

The same error occurred under Linux Ubuntu 20.04 with OpenSSL 1.1.1.

**Comment by johannesSX** [comment]
> Yes, exactly, I can't decipher it. Tried OpenSSL 1.1.1l on the Mac and got this error: `*** WARNING : deprecated key derivation used. Using -iter or -pbkdf2 would be better. bad decrypt 4357725696:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:610:`
> 
> I've tried password dozen of times.
> 
> The same error occurred under Linux Ubuntu 20.04 with OpenSSL 1.1.1.

It works! Solution: Download the file again through a different network.

**Comment by leiliew** [comment]
Great! I will close this issue for now then.
