### ISSUE TITLE
About normal data

### ISSUE THREAD

**Issue by RichardChangCA** [npnl/ATLAS#8]
Hello,

Thanks for your dataset, but I think the dataset only contains the stroke data without normal data. In my cases, I need both stoke data and normal data for comparison. Is there any normal data provided? If I find some other normal data online, I think the data distribution will be different with yours, which may have a negative impact on the performance.

Best,
Lingfeng

**Comment by leiliew** [comment]
Hello - no, we do not have normative data in this dataset - only stroke.
